### PR TITLE
Change withStates API to not force the user to create the final list themselves

### PR DESCRIPTION
**Pull request by Janiczek**
Proposed change:
```diff
-withStates : List String -> ClassName -> Attribute msg
+withStates : List ( String, Bool ) -> ClassName -> Attribute msg
```
So that the lib does the filtering and the user doesn't have to.

### CODE REVIEW

**Comment by Janiczek** [comment]
@turboMaCk ping :)
to refresh the memory, this copies the [`Html.Attributes.classList`](https://package.elm-lang.org/packages/elm/html/latest/Html-Attributes#classList) API and we're already using it in pro-next at few places.

**Comment by turboMaCk** [comment]
I'm fine with this change but maybe we should let @janjelinek and @kraklin vote on this as well.

**Comment by kraklin** [comment]
Seems OK to me. Another idea - how about to have `withState : (String, Bool) -> ClassName -> Html.Attribute msg` as there are a lot of cases where you need only one state, so why bother with `[]`

**Comment by turboMaCk** [comment]
because of `Html.Attribute msg` is opaque so once you produce it you won't be able to change it. Even though it's true that elm can merge multiple `class` attrs together this API would be super confusing.

the only way out would be `withState : (String, Bool) -> ClassName -> ClassName` which would then require extra `toClass` call and changes in internal data structure we're using here.

**Comment by kraklin** [comment]
OK, makes sense. Thanks.

**Comment by turboMaCk** [comment]
@Janiczek however I think you'll need to either make sure correct version of elm-test is instaled in CI or to mae tests compatible with neer version

**Comment by Janiczek** [comment]
Don't know what's the problem with Travis CI, so I'm going to wait a bit for replies on https://travis-ci.community/t/elm-test-fails-with-no-output-received-from-elm-make-when-searching-for-indirect-dependencies/2347

**Comment by turboMaCk** [comment]
@Janiczek maybe we need something like this? https://github.com/turboMaCk/queue/pull/3

**Comment by Janiczek** [comment]
@turboMaCk That's exactly what I'm doing: https://github.com/GlobalWebIndex/class-namespaces/pull/12/files#diff-354f30a63fb0907d4ad57269548329e3

**Comment by turboMaCk** [comment]
@Janiczek delete yarn.lock then. it's probably used for some detection of deps. Also feel free to remove `package.json`

**Comment by Janiczek** [comment]
@turboMaCk Thx!

**Pull request merged**
