### PR TITLE
WeakCss.nested, demo on ellie, code the same as on ellie

### PR DESCRIPTION
**Pull request by rofrol**

### CODE REVIEW

**Comment by turboMaCk** [comment]
Seems like we would need to update test for the newer version of elm-test...

**Comment by turboMaCk** [comment]
@rofrol can you fix it?

**Comment by turboMaCk** [comment]
@rofrol can you please rebase this branch? I think it will fix the failing tests.

**Comment by rofrol** [comment]
See this now.

**Pull request merged**
